### ISSUE TITLE
[Missing] add core info file for FBNeo

### ISSUE THREAD

**Issue by 5schatten** [libretro/libretro-core-info#13]
Looks like the dust has been settled a bit & the FinalBurn Neo repo https://github.com/libretro/FBNeo is up and running. So I guess a new FBNeo core info file will be needed?

I guess something like this could do the trick? But I guess it needs further tweaking for database files.
`fbneo_libretro.info`
```
display_name = "Arcade (FB Neo)"
authors = "Team FinalBurn Neo"
supported_extensions = "zip|7z"
corename = "FB Neo"
manufacturer = "Various"
categories = "Emulator"
systemname = "Arcade (various)"
systemid = "fb_alpha"
database = "FB Alpha - Arcade Games"
database_match_archive_member = "true"
license = "Non-commercial"
permissions = ""
display_version = "v0.2.97.44"
supports_no_game = "false"
notes = "(!) The BIOS files must be inside the ROM directory.|(!) You need a copy of neocdz.zip and neogeo.zip in your libretro system directory for neocd"
```

**Comment by RobLoach** [comment]
Thanks! Just ran an update.

```
git clone https://github.com/libretro/libretro-core-info.git
cd libretro-core-info
make update
```

It'll only be tagged once the new RA comes out though.

**Comment by RobLoach** [comment]
This should be fixed now. Feel free to re-open if it's not. Thanks!

**Comment by 5schatten** [comment]
@RobLoach 
I guess it should be fine & works for me. The only thing which might lead to confusion in the future is the system_id & database? I guess the fbalpha developement won't be that active anymore & if they share a common database that might contain unsupported stuff you'll run into problems.

**Comment by RobLoach** [comment]
You're right. Keep watch and let's see how the database may need to change.
