### ISSUE TITLE
[Beetle-DC] Reicast core info files needs updated name scheme

### ISSUE THREAD

**Issue by 5schatten** [libretro/libretro-core-info#14]
Since libretro-reicast is probably now https://github.com/libretro/beetle-dc the core-info file needs some adjustments too.

**Comment by hizzlekizzle** [comment]
Got it. Thanks for the heads-up.

**Comment by 5schatten** [comment]
@hizzlekizzle here we go again... https://github.com/libretro/flycast/commit/8f861517f57fab3d80a570ba7b7b58df24e9863e :confused:

**Comment by 5schatten** [comment]
@hizzlekizzle here we go again https://github.com/libretro/flycast/commit/8f861517f57fab3d80a570ba7b7b58df24e9863e :thinking:
