### ISSUE TITLE
[PS2] play! core information file is missing

### ISSUE THREAD

**Issue by 5schatten** [libretro/libretro-core-info#15]
I guess `libretro-core-info` should be updated before this can be merged https://github.com/libretro/Lakka-LibreELEC/pull/707

**Comment by RobLoach** [comment]
Lakka uses libretro-super sources directly:
https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/core-info/package.mk

Updated this repo either way :wink:
