### ISSUE TITLE
Version naming

### ISSUE THREAD

**Issue by guoyunhe** [libretro/libretro-core-info#18]
I saw the commit message says the new version is v1.7.9.2 but the git tag is v1.7.9-2. It is better to use the same version name everywhere. Also, dash can cause some trouble for packaging...

**Comment by RobLoach** [comment]
Thanks! Didn't know the sub-sub-version was breaking semver syntax. I'll tag `v1.7.9.2`.

**Comment by RobLoach** [comment]
Feel free to re-open if the tag isn't correct! https://github.com/libretro/libretro-core-info/releases/tag/v1.7.9.2

**Comment by guoyunhe** [comment]
That's good enough. Thanks!
