### ISSUE TITLE
TBG Dual has incorrect systemid

### ISSUE THREAD

**Issue by ZornTaov** [libretro/libretro-core-info#19]
https://github.com/libretro/libretro-core-info/blob/080b28a3266347ddda43def5306458dad211e9d4/tgbdual_libretro.info#L8
Going by what is used in other .info files, shouldn't this be "game_boy" instead?

**Comment by ZornTaov** [comment]
PR made https://github.com/libretro/libretro-super/pull/1156

**Comment by hizzlekizzle** [comment]
change is merged, closing.
