### ISSUE TITLE
[missing core info] Genesis-Plus-GX-Wide

### ISSUE THREAD

**Issue by SupervisedThinking** [libretro/libretro-core-info#36]
core info for https://github.com/libretro/Genesis-Plus-GX-Wide is missing and c'p does not work since not all systems are supported https://github.com/libretro/libretro-core-info/blob/master/genesis_plus_gx_libretro.info#L9 

Update here:
https://github.com/libretro/libretro-super/blob/master/dist/info/genesis_plus_gx_wide_libretro.info

@RobLoach could you bump the package please? 👍🏻

**Comment by RobLoach** [comment]
:+1:
