### ISSUE TITLE
Version 1.9.10 not tagged

### ISSUE THREAD

**Issue by tim77** [libretro/libretro-core-info#42]
` v1.9.10` released but not tagged. Please tag it to help maintainers with update.

**Comment by RobLoach** [comment]
Good catch. Seems the tag was missed.

**Comment by tim77** [comment]
@RobLoach sorry for disturbing you again - also this https://github.com/libretro/retroarch-joypad-autoconfig/issues/793.

**Comment by tim77** [comment]
@RobLoach and [this](https://github.com/libretro/libretro-database/issues/1215). Hope this is the last one. :)
