### ISSUE TITLE
[Request] Add .chd in ppsspp supported extension

### ISSUE THREAD

**Issue by Immersion95** [libretro/libretro-core-info#62]
Is it possible to add the extrension ? I wanted to create the PR but didn't know if only modifying the core info file would be enough.

https://github.com/hrydgard/ppsspp/pull/18198

**Comment by hizzlekizzle** [comment]
lol I came here to say "hrydgard has already said he's not into it" but it seems he's come around (even if just to silence the requests).

Try loading one from a command line. If it works there, then yes, just adding the extension to the list in the info file is enough.

**Comment by RobLoach** [comment]
https://github.com/libretro/libretro-super/tree/master/dist/info
