### ISSUE TITLE
Add mednafen_saturn_hw_libretro.info

### ISSUE THREAD

**Issue by crocket** [libretro/libretro-core-info#8]
I built mednafen-saturn-libretro with opengl support on Gentoo.
It produced mednafen_saturn_hw_libretro.so which is not in libretro-core-info.

**Comment by twinaphex** [comment]
There is no OpenGL renderer in Mednafen Saturn though. So this would be quite useless to add.

**Comment by crocket** [comment]
mednafen saturn utilizes OpenGL shaders.
Refer to https://mednafen.github.io/documentation/ss.html for details.

**Comment by hizzlekizzle** [comment]
Those are post-processing shaders. The emulator itself is completely software-rendered and doesn't utilize shaders internally.

**Comment by crocket** [comment]
Why does beetle-saturn-libretro's Makefile have OpenGL build option?

**Comment by fr500** [comment]
Because we have a generic makefile we adapt to the situation

**Comment by RobLoach** [comment]
mednafen_saturn_hw isn't built in BuildBot:
https://buildbot.libretro.com/nightly/linux/x86_64/latest/

Once Mednafen-Saturn gets OpenGL directly in the emulator itself, then it may make sense to add it to buildbot. Until then, sounds like this one is :+1: .

Thanks for bringing this up, @crocket! Glad you're looking to improve the info files.
